### ISSUE TITLE
ReferenceError: performance is not defined

### ISSUE THREAD

**Issue by moltar** [tajo/ladle#221]
**Describe the bug**

Works locally, but getting the following error in CI:

> ReferenceError: performance is not defined

```yml
  ladle-build:
    needs: install
    runs-on: ubuntu-latest
    name: Ladle Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install NPM 8
        run: npm install -g npm@8

      - name: Install
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          install-command: npm ci

      - name: Build Ladle
        run: npx ladle build
```

**Environment**

 - OS: linux
 - Browser N/A
 - Version `"@ladle/react": "2.1.0",`
